name: 'Publish Github Action'

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm run build
          npm run package

      - name: Test
        run: npm run test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: dist
          path: dist/
